#!/bin/bash

set -e

ask () {
    read -p "> $1 " -r
    echo
}

print () {
    echo -e "\n\033[1m> $1\033[0m\n"
}
  echo "Partitioning Drive"
  # EFI Partition
  sgdisk -Zo "$DISK"
  while true; do
    ask "Size of EFI Partition in [MiB]. Minimum is 512 MiB:"
    if (( "$REPLY" >= 512 )); then break; else print "Oops. Too small, $REPLY is less than minimum is 512 [MiB]"; fi
  done
  sgdisk -n1:1M:+"$REPLY"M -t1:EF00 "$DISK"
  EFI="$DISK-part1"

  ask "Do you want a Swap Partition?"
      if [[ $REPLY =~ ^[Yy]$ ]]
      then
        ask "Do you want Resume Support (Requires SWAP > MEMORY)?"
          if [[ $REPLY =~ ^[Yy]$ ]]; then
            SWAPRESUME=1
            SWAPMIN=$(free -h | sed -n '2p' | awk '{ print $2 }')
            SWAPMIN=$(( ${SWAPMIN::-2} + 2 ))
            while true; do
              ask "Size of Swap Partition in [GiB]? Minimum is $SWAPMIN GiB"
              if (( "$REPLY" >= "$SWAPMIN" )); then break;
              else
                print "Oops. Too small, $REPLY GiB is less than minimum $SWAPMIN GiB for Resume Support"
                ask "Do you wish to still have Resume Support?"
                if [[ $CHECK =~ ^[Yy]$ ]]; then
                  SWAPRESUME=1
                else
                  unset SWAPRESUME
                  ask "Size of Swap Partition in [GiB]?"
                  break
                fi
              fi
            done
          else
            ask "Size of Swap Partition in [GiB]?"
          fi
          sgdisk -n2:0:+"$REPLY"G -t2:8200 "$DISK"
          SWAPPART="$DISK-part2"
      fi

  # ZFS Partition
  sgdisk -n3:0:0 -t3:BF00 "$DISK"
  ZFS="$DISK-part3"

  # notify Kernel
  partprobe "$DISK"

  # Format EFI Partition
  sleep 1
  echo "Formatting EFI Partition"
  mkfs.vfat -F32 "$EFI"
else
  if [[ -z "$EFI" ]]; then
    print "Select EFI Partition"
    select ENTRY in $(ls "$DISK"-part*);
    do
      print "Reusing $ENTRY as EFI partition"
      echo "This does not change partition"
      EFI=$ENTRY
      break
    done
  fi
  if [[ -z "$ZFS" ]]; then
    print "Select ZFS Root Partition"
    select ENTRY in $(ls "$DISK"-part*);
    do
      print "Reusing $ENTRY as ZFS Root partition"
      echo "This does not change partition"
      ZFS=$ENTRY
      break
    done
  fi
  if [[ -z $SWAPPART ]]; then
    ask "Do you have a Swap Partition?"
      if [[ $REPLY =~ ^[Yy]$ ]]; then
        select ENTRY in $(ls "$DISK"-part*);
        do
          print "Reusing $ENTRY as Swap partition"
          echo "This does not change partition settings"
          SWAPPART=$ENTRY
          break
        done
      fi
  fi
fi
