#!/bin/sh

build() {
    add_all_modules "/char/tpm/"
    add_binary "bash"
    add_binary "tr"
    add_binary "grep"
    add_binary "sed"

    for _LIBRARY in /usr/bin/clevis*; do
        add_binary "${_LIBRARY}"
    done

    add_binary "jose"
    add_binary "tpm2_createprimary"
    add_binary "tpm2_load"
    add_binary "tpm2_unseal"
    add_binary "tpm2_flushcontext"

    for _LIBRARY in /usr/lib/libtss2-tcti-device.so*; do
        if [ -e "${_LIBRARY}" ]; then
            add_binary "${_LIBRARY}"
        fi
    done

    add_runscript
}

help() {
    cat <<HELPEOF
This hook will decrypt a file stored at /keys/secret.jwe with clevis-decrypt-tpm2 and store it at /etc/zfs/zroot.key:
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
