#!/usr/bin/ash

run_hook(){
	if [ -f /keys/secret.jwe ]; then
		clevis-decrypt-tpm2 < /keys/secret.jwe > /etc/zfs/zroot.key
	fi
}

run_cleanuphook(){
    if [ -f /etc/zfs/zroot.key ]; then
        rm /etc/zfs/zroot/key
    fi
}
# vim:set ts=4 sw=4 ft=sh et:
